DROP TABLE IF EXISTS `ofertas`;
CREATE TABLE `ofertas` (
  `ofertas_id_oferta` INTEGER NOT NULL, -- AUTO_INCREMENT,
  `ofertas_id_empresa` INTEGER NOT NULL,
  `ofertas_id_ocupacion` INTEGER NOT NULL,
  `ofertas_meses_experiencia` INTEGER NOT NULL,
  `ofertas_id_formacion` INTEGER NOT NULL,
  `ofertas_id_carnet_conducir` INTEGER NOT NULL,
  `ofertas_id_vehiculo` INTEGER NOT NULL,
  `ofertas_id_municipio` INTEGER NOT NULL,
  `ofertas_id_provincia` INTEGER NOT NULL,
  `ofertas_puesto_descripcion` BLOB NOT NULL,
  `ofertas_id_contrato` INTEGER NOT NULL,
  `ofertas_id_jornada` INTEGER NOT NULL,
--   `ofertas_convenio` blob NOT NULL,
  `ofertas_salario` INTEGER NOT NULL DEFAULT '0',
  `ofertas_id_estado_oferta` INTEGER NOT NULL,
  `ofertas_fecha_creacion` date DEFAULT NULL,
  `ofertas_fecha_finalizacion` date DEFAULT NULL,
  `ofertas_priorityField1` BOOLEAN DEFAULT NULL,
  `ofertas_priorityField2` BOOLEAN DEFAULT NULL,
  `ofertas_priorityField3` BOOLEAN DEFAULT NULL,
  `ofertas_priorityField4` BOOLEAN DEFAULT NULL,
  PRIMARY KEY (`ofertas_id_oferta`),
  UNIQUE (`ofertas_id_oferta`),
  FOREIGN KEY (`ofertas_id_carnet_conducir`) REFERENCES `carnets` (`carnets_id_carnet`) ON DELETE CASCADE,
  FOREIGN KEY (`ofertas_id_contrato`) REFERENCES `contratos` (`contratos_id_contrato`) ON DELETE CASCADE,
  FOREIGN KEY (`ofertas_id_empresa`) REFERENCES `empresas` (`empresas_id_empresa`) ON DELETE CASCADE,
  FOREIGN KEY (`ofertas_id_estado_oferta`) REFERENCES `estados_ofertas` (`estados_ofertas_id_estado_oferta`) ON DELETE CASCADE,
  FOREIGN KEY (`ofertas_id_formacion`) REFERENCES `formaciones` (`formaciones_id_formacion`) ON DELETE CASCADE,
  FOREIGN KEY (`ofertas_id_jornada`) REFERENCES `jornadas` (`jornadas_id_jornada`) ON DELETE CASCADE,
  FOREIGN KEY (`ofertas_id_municipio`) REFERENCES `municipios` (`municipios_id_municipio`) ON DELETE CASCADE,
  FOREIGN KEY (`ofertas_id_ocupacion`) REFERENCES `ocupaciones` (`ocupaciones_id_ocupacion`) ON DELETE CASCADE,
  FOREIGN KEY (`ofertas_id_provincia`) REFERENCES `provincias` (`provincias_id_provincia`) ON DELETE CASCADE,
  FOREIGN KEY (`ofertas_id_vehiculo`) REFERENCES `vehiculos` (`vehiculos_id_vehiculo`) ON DELETE CASCADE
); -- ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci
